#!/usr/bin/env python3
"""The publisher's own readers must never meet the network.

Jason Velazquez at Greylock Glass has monthly contributors, and asked that they
not be charged at his own site. The answer is that anyone signed in to the
WordPress site who did not arrive through the network reads everything on it --
no meter, no gate, no price quote. A newspaper's own relationships are not the
network's to intermediate.

This asserts that, and asserts the control alongside it: the *same URL*, on the
same site, in the same run, must still gate a reader who is not signed in. A
test that only checked the subscriber gets through would pass just as happily on
a site where nothing is priced at all, which is the failure this project keeps
finding. So each site proves both halves or neither counts.

The third check is the role guard. A network account holds newshare_guest and
nothing else; if its link meta is lost the account must still be gated, not
silently promoted into the publisher's own audience.

Creates two throwaway users per site and deletes them afterwards, including on
failure.

Usage:  infra/local-reader-test.py
Exit:   0 if every site passes all three, 1 otherwise.
"""
from __future__ import annotations

import subprocess
import sys
import urllib.error
import urllib.request

PUBLISHERS = {
    "barharbor":      ("Bar Harbor",        "https://barharbor.info"),
    "northberkshire": ("North Berkshire",   "https://northberkshire.org"),
    "wesmc":          ("West End Sentinel", "https://wesmc.org"),
}

# ssh account and document root per site. West End Sentinel is an addon domain
# under the northberkshire account, so it shares the login and not the docroot.
SITE_HOSTS = {
    "barharbor":      ("barharbor",      "public_html"),
    "northberkshire": ("northberkshire", "public_html"),
    "wesmc":          ("northberkshire", "wesmc.org"),
}

GATE_MARKER = "newshare-access-gate"
UA = "Mozilla/5.0 (newshare local-reader-test)"

PASS: list[str] = []
FAIL: list[str] = []


def ok(label: str, detail: str = "") -> None:
    print(f"  \033[32m✓\033[0m {label:<46} {detail}")
    PASS.append(label)


def bad(label: str, detail: str = "") -> None:
    print(f"  \033[31m✗\033[0m {label:<46} {detail}")
    FAIL.append(label)


def wp(site: str, command: str, timeout: int = 90) -> str:
    """Run a wp-cli command in the site's document root."""
    account, docroot = SITE_HOSTS[site]
    out = subprocess.run(
        ["ssh", "-o", "BatchMode=yes", f"{account}@svaha.com",
         f"export PATH=~/bin:$PATH; cd ~/{docroot}; {command}"],
        capture_output=True, text=True, timeout=timeout)
    return out.stdout.strip()


def walk(urls: list[str], cookie: str = "") -> str | None:
    """Read down the list carrying cookies forward; return the first URL that gates.

    The meter is the reason this walks rather than fetching once. A single
    request to a priced article is served to anybody -- the first three are free
    -- so a check that fetched the gated URL cold would report success for a
    reader who is not exempt at all, and would have passed before the exemption
    existed. Burning the meter the same way for every reader is what makes the
    comparison mean anything.

    Cookies are carried by hand rather than by http.cookiejar, which refuses to
    add its own header to a request that already carries one: passing the login
    cookie that way silently dropped the meter cookie on every hop, and both
    readers sailed through all four articles for the same wrong reason.
    """
    jar: dict[str, str] = {}
    if cookie:
        name, _, value = cookie.partition("=")
        jar[name] = value

    for url in urls:
        headers = {"User-Agent": UA}
        if jar:
            headers["Cookie"] = "; ".join(f"{k}={v}" for k, v in jar.items())
        req = urllib.request.Request(url, headers=headers)
        try:
            with urllib.request.urlopen(req, timeout=45) as r:
                body = r.read().decode("utf-8", "replace")
                setc = r.headers.get_all("Set-Cookie") or []
        except urllib.error.HTTPError as e:
            body = e.read().decode("utf-8", "replace")
            setc = e.headers.get_all("Set-Cookie") or []
        for raw in setc:
            name, _, value = raw.split(";", 1)[0].partition("=")
            if name.strip():
                jar[name.strip()] = value
        if GATE_MARKER in body:
            return url
    return None


def login_cookie(site: str, user_id: str) -> str:
    """A logged-in cookie for a user, generated by WordPress itself.

    wp_generate_auth_cookie with the logged_in scheme is what wp-login.php sets
    on a successful sign-in, so this is the same session an ordinary reader gets
    without having to drive the login form.
    """
    php = ('echo LOGGED_IN_COOKIE . "=" . '
           f'wp_generate_auth_cookie( {user_id}, time() + 3600, "logged_in" );')
    return wp(site, f"wp eval {php!r}")


def make_user(site: str, login: str, role: str) -> str:
    out = wp(site, f"wp user create {login} {login}@example.invalid "
                   f"--role={role} --porcelain")
    return out.splitlines()[-1].strip() if out else ""


def delete_user(site: str, login: str) -> None:
    wp(site, f"wp user delete {login} --yes --reassign=1 >/dev/null 2>&1 || true")


def check_site(site: str) -> None:
    label, base = PUBLISHERS[site]
    print(f"\n\033[1m{label}\033[0m  {base}")

    urls = wp(site, "wp post list --post_type=post --post_status=publish "
                    "--posts_per_page=8 --field=url").split()
    if len(urls) < 4:
        bad(f"{label}: articles to read", f"only {len(urls)}")
        return

    gated = walk(urls)
    if not gated:
        bad(f"{label}: an article gates an anonymous reader",
            "none of the first 8 gated -- nothing here is priced")
        return
    # Everything up to and including the article that stopped the anonymous
    # reader. Each reader below walks exactly this, so each burns the same meter.
    run = urls[:urls.index(gated) + 1]
    ok(f"{label}: an article gates an anonymous reader",
       f"stopped at #{len(run)} of {len(urls)}")

    subscriber = f"nstest_sub_{site[:6]}"
    guest = f"nstest_guest_{site[:6]}"
    delete_user(site, subscriber)
    delete_user(site, guest)

    try:
        sub_id = make_user(site, subscriber, "subscriber")
        if not sub_id.isdigit():
            bad(f"{label}: create a local subscriber", sub_id[:60])
            return

        stopped = walk(run, login_cookie(site, sub_id))
        if stopped:
            bad(f"{label}: the publisher's subscriber is not gated",
                f"gated at #{run.index(stopped) + 1} of {len(run)}")
        else:
            ok(f"{label}: the publisher's subscriber is not gated",
               f"read all {len(run)} in full")

        guest_id = make_user(site, guest, "newshare_guest")
        if not guest_id.isdigit():
            bad(f"{label}: create a guest-role account", guest_id[:60])
            return

        stopped = walk(run, login_cookie(site, guest_id))
        if stopped:
            ok(f"{label}: a guest-role account is still gated",
               "role guard holds without link meta")
        else:
            bad(f"{label}: a guest-role account is still gated",
                f"newshare_guest read all {len(run)} for free")
    finally:
        delete_user(site, subscriber)
        delete_user(site, guest)


def main() -> int:
    print("\033[1mThe publisher's own readers\033[0m")
    for site in PUBLISHERS:
        try:
            check_site(site)
        except subprocess.TimeoutExpired:
            bad(f"{PUBLISHERS[site][0]}: reachable", "ssh timed out")

    print(f"\n  {len(PASS)} passed, {len(FAIL)} failed")
    for f in FAIL:
        print(f"    \033[31m✗\033[0m {f}")
    return 1 if FAIL else 0


if __name__ == "__main__":
    sys.exit(main())
